Traveller/urls.py
from django.contrib import admin
from django.urls import path,include  
from home.views import *
from livestreams.views import *
from maps.views import *
from chats.views import *
from notifications.views import *
from dashboard.views import *
from search.views import *
from home.views import home, user_login, user_register, user_logout

urlpatterns = [
   path('', include('home.urls', namespace='home')),
#    path('dashboard/', include('dashboard.urls')),
    path('livestreams/',livestreams,name="livestreams"),
    path('maps/',maps,name="maps"),
    path('chats/',chats,name="chats"),
#    path('notifications/',notifications,name="notifications"),
    path('search/',search,name="search"),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
# dashboard/urls.py

from django.urls import path
from . import views

urlpatterns = [
    # other paths...
    # other paths...
]

home/urls.py
# home/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),  # Add this line to handle the root URL
    path('home/', home, name='home'),
    path('login/', user_login, name='user_login'),
    path('register/', user_register, name='user_register'),
    path('logout/', user_logout, name='user_logout'),
    path('dashboard/', dashboard, name='dashboard'),
    path('dashboard/<int:user_id>/', dashboard, name='user_dashboard'),
    path('dashboard/<str:username>/', dashboard, name='user_dashboard_by_username'),
    path('follow/<int:user_id>/<int:action>/', follow, name='follow'),
    path('maps/', maps, name='maps'),
    path('create_post/', create_post, name='create_post'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('like/<uuid:post_id>/', like, name='like'),
    path('chats/', inbox, name='message'),
   	path('chats/direct/<username>', Directs, name='directs'),
   	path('chats/new/', UserSearch, name='search-users'),
   	path('chats/new/<username>', NewConversation, name='conversation'),
   	path('chats/send/', SendDirect, name='send-directs'),
    path('notifications/', ShowNOtifications, name='show-notifications'),
   	path('notifications/<noti_id>/delete', DeleteNotification, name='delete-notification'),
    # path('conversation/<int:user_id>/', conversation, name='conversation'),
    # path('<username>/', UserProfile, name='profile'),
    # path('<username>/saved/', UserProfile, name='profilefavourite'),
    # path('<username>/follow/<option>/', follow, name='follow'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Max
from django.forms import DateTimeField


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="from_user")
    reciepient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="to_user")
    body = models.TextField(null=True)
    date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def sender_message(from_user, to_user, body):
        sender_message = Message(
            user=from_user,
            sender = from_user,
            reciepient = to_user,
            body = body,
            is_read = True
            )
        sender_message.save()
    
        reciepient_message = Message(
            user=to_user,
            sender = from_user,
            reciepient = from_user,
            body = body,
            is_read = True
            )
        reciepient_message.save()
        return sender_message

    def get_message(user):
        users = []
        messages = Message.objects.filter(user=user).values('reciepient').annotate(last=Max('date')).order_by('-last')
        for message in messages:
            users.append({
                'user': User.objects.get(pk=message['reciepient']),
                'last': message['last'],
                'unread': Message.objects.filter(user=user, reciepient__pk=message['reciepient'], is_read=False).count()
            })
        return users
            

maps/models.py
from django.db import models

home/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from dashboard.models import *
class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use. Please use a different email address.")
        return email


class ProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False)
    bio = forms.CharField(widget=forms.Textarea)
    location = forms.CharField(max_length=100)

    class Meta:
        model = Profile
        fields = ['profile_picture', 'bio', 'location']



class PostForm(forms.ModelForm):
    picture = forms.ImageField(required=True)
    caption = forms.CharField(widget=forms.Textarea(attrs={'class':'input is-medium'}), required=True)
    location = forms.CharField(widget=forms.TextInput(attrs={'class':'input is-medium'}), required=True)

    class Meta:
        model = Post
        fields = ('picture', 'caption', 'location')

chats/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required
from django.template.loader import get_template 

from chats.models import Message
# Create your views here.

@login_required
def chats(request):
    user = request.user
    messages = Message.get_messages(user=user)
    active_direct = None
    directs = None

    if messages:
        message = messages[0]
        active_direct = message['user'].username
        directs = Message.objects.filter(user=user, recipient=message['user'])
        directs.update(is_read = True)

        for message in messages:
            if message['user'].username == active_direct:
                message['unread'] = 0
        
        context = {
            'directs': directs,
            'messages': messages,
            'active_direct': active_direct
        }


    return render(request, 'chats.html', context)

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse



def user_logout(request):
    logout(request)
    return redirect('home:user_login')

def dashboard(request):
    return render(request, "dashboard.html")

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from dashboard.models import *
from django.http import JsonResponse, HttpResponseNotFound
from django.core.files.storage import default_storage
import json
import requests
from django.template.loader import get_template 
from chats.models import Message
from django.core.paginator import Paginator
from django.db.models import Q

from bs4 import BeautifulSoup
import random

from uuid import UUID

#follow
@login_required
def follow(request, user_id, action):
    user_to_follow = get_object_or_404(User, id=user_id)
    current_user = request.user

    if action == 1:
        # Follow the user
        if current_user != user_to_follow:
            follow, created = Follow.objects.get_or_create(follower=current_user, following=user_to_follow)
            messages.success(request, f'You are now following {user_to_follow.username}.')
            if created:
                # Add all posts of the followed user to the follower's stream
                posts = Post.objects.filter(user=user_to_follow)
                for post in posts:
                    Stream.objects.get_or_create(
                        post=post,
                        user=current_user,
                        date=post.posted,
                        following=user_to_follow
                    )

        
    elif action == 0:
        # Unfollow the user
        follow_instance = Follow.objects.filter(follower=current_user, following=user_to_follow).first()
        if follow_instance:
            follow_instance.delete()
            Stream.objects.filter(user=current_user, following=user_to_follow).delete()

            messages.success(request, f'You have unfollowed {user_to_follow.username}.')
        else:
            messages.error(request, 'You are not following this user.')

    return redirect(request.META.get('HTTP_REFERER', 'home:dashboard'))  # Redirect back to the previous page or dashboard

#webscraping

def fetch_article():
    url = 'https://www.lonelyplanet.com/articles'

    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')

    articles = soup.find_all('article')
    if(articles):
        n = random.randint(0, len(articles)-1)
        article = articles[n]
            # Extract article details
        img_tag = article.find('img')
        img_url = img_tag['src'] if img_tag else None
        title_tag = article.find('a')
        title = title_tag.text.strip() if title_tag else None
        rel_url = title_tag['href'] if title_tag else None
        description_tag = article.find('p', class_='text-sm')
        description = description_tag.text.strip() if description_tag else None
        base_url = 'https://www.lonelyplanet.com'
        link = base_url+rel_url

    return title, link, img_url, description


# notifications
def ShowNOtifications(request):
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date')
    Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)

    title, link, img_url, description = fetch_article()
    article = {
        'title': title,
        'link': link,
        'img_url': img_url,
        'description': description
    }
    
    context = {
        'notifications': notifications,
        'article': article  # Added article to context if needed
    }
    
    return render(request, 'notifications.html', context)


def DeleteNotification(request, noti_id):
	user = request.user
	Notification.objects.filter(id=noti_id, user=user).delete()
	return redirect('home:show-notifications')


def CountNotifications(request):
	count_notifications = 0
	if request.user.is_authenticated:
		count_notifications = Notification.objects.filter(user=request.user, is_seen=False).count()

	return {'count_notifications':count_notifications}
	


#messages
@login_required
def inbox(request):
    user = request.user
    messages = Message.get_message(user=request.user)
    active_direct = None
    directs = None
    profile = get_object_or_404(Profile, user=user)

    if messages:
        message = messages[0]
        active_direct = message['user'].username
        directs = Message.objects.filter(user=request.user, reciepient=message['user'])
        directs.update(is_read=True)

        for message in messages:
            if message['user'].username == active_direct:
                message['unread'] = 0
    context = {
        'directs':directs,
        'messages': messages,
        'active_direct': active_direct,
        'profile': profile,
    }
    return render(request, 'chats.html', context)


@login_required
def Directs(request, username):
    user  = request.user
    messages = Message.get_message(user=user)
    active_direct = username
    directs = Message.objects.filter(user=user, reciepient__username=username)  
    directs.update(is_read=True)

    for message in messages:
            if message['user'].username == username:
                message['unread'] = 0
    context = {
        'directs': directs,
        'messages': messages,
        'active_direct': active_direct,
    }
    return render(request, 'chats.html', context)

def SendDirect(request):
    from_user = request.user
    to_user_username = request.POST.get('to_user')
    body = request.POST.get('body')

    if request.method == "POST":
        to_user = User.objects.get(username=to_user_username)
        Message.sender_message(from_user, to_user, body)
        return redirect('home:message')

def UserSearch(request):
    query = request.GET.get('q')
    context = {}
    if query:
        users = User.objects.filter(Q(username__icontains=query))

        # Paginator
        paginator = Paginator(users, 8)
        page_number = request.GET.get('page')
        users_paginator = paginator.get_page(page_number)

        context = {
            'users': users_paginator,
            }

    return render(request, 'search_users.html', context)

def NewConversation(request, username):
    from_user = request.user
    body = ''
    try:
        to_user = User.objects.get(username=username)
    except Exception as e:
        return redirect('home:search-users')
    if from_user != to_user:
        Message.sender_message(from_user, to_user, body)
    return redirect('home:message')

#maps
@login_required
def maps(request):
    user = request.user
    followings = Follow.objects.filter(follower=user).select_related('following')
    following_list = []
    locations = []
    for follow in followings:
        user_followed = Profile.objects.get(user=follow.following)
        following_list.append(user_followed)
        
        response = requests.get("https://nominatim.openstreetmap.org/search?format=json&limit=1&q='"+ user_followed.location)
        if response.status_code == 200:

            data = response.json()

            if(data):
                lat = float(data[0]["lat"])
                lon = float(data[0]["lon"])
                tag = str(user_followed.user)
                locations.append([lat,lon,tag])
        else:
            print("No data received")

    context = {
        'following_list': following_list,
        'locations': json.dumps(locations)
    }
    return render(request, 'maps.html', context)

# DASHBOARD
@login_required
def dashboard(request, user_id=None):
    if user_id is None:
        user = request.user
    else:
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            return HttpResponseNotFound("User not found")
        # Ensure user has a profile
    if not hasattr(user, 'profile'):
        Profile.objects.create(user=user)

    profile = user.profile  # Get the profile associated with the logged-in user

    followers = Follow.objects.filter(following=user)
    followings = Follow.objects.filter(follower=user)

    post_items = Post.objects.filter(user=user)
    liked_posts = Likes.objects.filter(user=user).values_list('post_id', flat=True)
    post_items_with_likes = [
        {
            'post': post,
            'liked': post.id in liked_posts
        }
        for post in post_items
    ]

    # Set profile variables
    profile.followers_count = followers.count()
    profile.following_count = followings.count()
    profile.places_travelled = post_items.count()
    profile.save()

    follow_status = Follow.objects.filter(follower=request.user, following=profile.user).exists()

    print(f"User ID: {user.id}")  # Debugging line
    print(f"followings: {followings.count()}")  # Debugging line

    #edit profile
    if request.method == 'POST' and user_id is None:
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return redirect('home:dashboard') # Redirect to dashboard or another page upon successful form submission
    else:
        form = ProfileForm(instance=request.user.profile)  # Create form for current user's profile data
    
    
    context = {
        'profile': profile,
        'post_items_with_likes': post_items_with_likes,
        'form':form,
        'follow_status':follow_status
    }
    return render(request, 'dashboard.html', context)

# new post
def create_post(request):
    user = request.user
    if request.method == 'POST':
        postform = PostForm(request.POST, request.FILES)
        if postform.is_valid():
            picture = postform.cleaned_data.get('picture')
            caption = postform.cleaned_data.get('caption')
            location = postform.cleaned_data.get('location')

            # Create or get the post
            post, created = Post.objects.get_or_create(picture=picture, caption=caption, location=location, user=user)
            

livestreams/views.py
from django.shortcuts import render
from django.http import HttpResponse


def livestreams(request):
    return render(request, "livestreams.html")

maps/views.py
from django.shortcuts import render
from django.http import HttpResponse


def maps(request):
    return render(request, "maps.html")

notifications/views.py
from django.shortcuts import render


def notifications(request):
    return render(request, "notifications.html")

# Create your views here.

search/views.py
from django.shortcuts import render
from django.http import HttpResponse


def search(request):
    return render(request, "search.html")

home/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block start %}

<head>

    <style>
        .profile-container {
            display: flex;
            justify-content: center;
            /* align-items: center; */

        }

        .button-card {
            display: inline-flex;
            align-items: center;
            color: white;
            border: 1px solid #ddd;
            border-radius: 8px;
            cursor: pointer;
            margin-bottom: 10px;
            transition: background-color 0.3s;
        }
        .follow-button-card {
            display: flex;
            align-items: center;
            justify-content: center;
            color: azure;
            border: 1px solid #ddd;
            border-radius: 8px;
            cursor: pointer;
            margin-top: 10px;
            padding: 8px;
            transition: background-color 0.3s;
        }
        .unfollow-button-card {
            display: flex;
            align-items: center;
            justify-content: center;
            color: azure;
            border: 1px solid #ddd;
            border-radius: 8px;
            cursor: pointer;
            margin-top: 10px;
            padding: 8px;
            transition: background-color 0.3s;
        }
        
        .unfollow-button-card:hover{
            color: red;
            background-color: azure;
        }
        .follow-button-card:hover{
            color: green;
            background-color: azure;
        }
        .button-card:hover {
            background-color: azure;
        }

        .button-card i {
            margin-left: 10px;
            /* Adjust as needed */
            margin-top: 10px;
            margin-bottom: 10px;
            margin-right: 6px;
            
        }

        .button-container {
            display: flex;
            padding-top: 50px;
            flex-direction: column;
        }

        .profile-section {
            display: flex;
            justify-content: center;
            /* Center horizontally */
            align-items: center;
            /* Center vertically */
            flex-direction: column;
            color: #ddd;
        }

        .h2 {
            margin-top: 100px;
        }


        /* Style for the like icon */
        .like-icon {
            cursor: pointer;
            /* Change cursor to pointer */
            font-size: 1.5rem;
            /* Adjust the size as needed */
            transition: color 0.3s;
            /* Smooth transition for color change */
        }


        /* Color when the heart icon is liked */
        .like-icon.fas {
            color: red;
            /* Color when liked */
        }
    </style>
</head>

<div class="profile-container">
    <div class="profile-card">
        <div class="profile-header">
            <div class="profile-section">
                <h2>@{{ profile.user.username }}</h2>
                <div class="profile-picture">
                    {% if profile.profile_picture %}
                    <img src="{{ profile.profile_picture.url }}" , alt="Profile Picture" ,
                        placeholder="https://picsum.photos/200/300">
                    {% endif %}
                </div>
                <h6 class="mt-3">last seen in: {{ profile.location }}</h6>
            </div>

            <div class="profile-info">
                <div class="profile-stats">
                    <div>
                        Places Travelled<br>
                        <strong>{{ profile.places_travelled }}</strong>
                    </div>
                    <div>
                        Followers<br>
                        <strong>{{ profile.followers_count }}</strong>
                    </div>
                    <div>
                        Following<br>
                        <strong>{{ profile.following_count}}</strong>
                    </div>
                </div>

                <div class="profile-bio">
                    <h4 style="color: #FFBD59;"> Bio </h4>
                    <p>{{ profile.bio }}</p>
                </div>

                {% if request.user.is_authenticated and request.user != profile.user %}
                {% if follow_status == True %}
                <a href="{% url 'home:follow' profile.user.id 0 %}" class="unfollow-button-card">Unfollow</a>
                {% else %}
                <a href="{% url 'home:follow' profile.user.id 1 %}" class="follow-button-card">Follow</a>
                {% endif %}
    
                {% endif %}
                
            </div>


        </div>
    </div>
    {% if request.user.is_authenticated and request.user == profile.user %}
    <div class="button-container">
        <a href="{% url 'home:create_post' %}" class="button-card">
            <i class="fas fa-plus"></i> <!-- Font Awesome plus icon -->
        </a>
        <a href="{% url 'home:edit_profile' %}" class="button-card">
            <i class="fas fa-edit"></i> <!-- Font Awesome plus icon -->
        </a>
        <a href="{% url 'home:user_logout' %}" class="button-card">
            <i class="fa fa-sign-out-alt"></i> <!-- Font Awesome plus icon -->
        </a>
    </div>
    {% endif %}
</div>

<!-- Posts -->
<div class="container">
    <div class="row">
        {% if post_items_with_likes %}
        {% for item in post_items_with_likes %}
        <div class="col-md-4 col-sm-6 col-12 mt-3 mb-3">
            <div class="card custom-card">
                <div class="row post-header col-12 py-2 px-3">
                    <div class="col-6 float-left">
                        <h4 style="font-weight: 600;">{{ item.post.location }}</h4>
                    </div>
                </div>
                <div class="custom-img-container">
                    <img class="card-img custom-img" src="{{ item.post.picture.url }}" alt="{{ item.post.location }}">
                </div>
                <div class="card-body px-3">
                    <div class="d-flex justify-content-between align-items">
                        <h5 class="card-title" style="font-weight: 600;">@{{ item.post.user }}</h5>
                        <div class="d-flex">
                            <h5 class="card-title mr-1" id="like-count-{{ item.post.id }}">{{ item.post.likes }}</h5>
                            {% if item.liked %}
                            <i class="fa-heart fas like-icon" id="like-icon-{{ item.post.id }}"
                                data-post-id="{{ item.post.id }}"></i>
                            {% else %}
                            <i class="fa-heart far like-icon" id="like-icon-{{ item.post.id }}"
                                data-post-id="{{ item.post.id }}"></i>
                            {% endif %}

                        </div>
                    </div>
                    <p class="card-text">{{ item.post.caption }}</p>
                </div>

            </div>
        </div>
        {% endfor %}
        {% else %}
        <p style="color:azure">No posts yet.</p>
        {% endif %}
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        document.querySelectorAll(".like-icon").forEach(function (icon) {
            icon.addEventListener("click", function () {
                const postId = this.getAttribute("data-post-id");
                const likeCountElement = document.getElementById(`like-count-${postId}`);
                const iconElement = this; // Current clicked icon

                fetch(`/like/${postId}/`, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "X-CSRFToken": "{{ csrf_token }}"
                    },
                    credentials: "same-origin"
                })
                    .then(response => response.json())
                    .then(data => {
                        // Update like count
                        likeCountElement.textContent = data.likes;

                        // Toggle icon classes
                        if (iconElement.classList.contains("far")) {
                            iconElement.classList.remove("far");
                            iconElement.classList.add("fas");
                        } else {
                            iconElement.classList.remove("fas");
                            iconElement.classList.add("far");
                        }
                    })
                    .catch(error => console.error('Error:', error));
            });
        });
    });
</script>
{% endblock %}

home/templates/livestreams.html
{% extends 'base.html' %}
{% block start %}
This is LIVESTREAMS
{% endblock %}

home/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Traveller</title>
    <!-- Bootstrap CSS -->
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    
    <div class="body login-page">
        <div class="login-card">
            <div class="card-body">
                <h2 class="card-title">LOGIN</h2>
                <form method="post" action="{% url 'home:user_login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username:</label>
                        <input type="text" id="username" name="username" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Password:</label>
                        <input type="password" id="password" name="password" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
                <p style="font-size: 18px; text-align: left; margin-bottom: 0;">
                    Don't have an account? <a href="{% url 'home:user_register' %}" class="register-link" style="display: inline;">Register here</a>
                </p>
                                                          
            </div>
        </div>
    </div>
</body>
</html>

home/templates/maps.html
{% extends 'base.html' %}
{% block start %}

<head>
    <style>
        .col-md-3 {
            padding-top: 25px;
            padding-left: 0px;
            padding-right: 20px;
            overflow-y: hidden;
        }
    </style>
</head>
<div class="container-fluid">
    <div class="row justify-content-center">

        <div class="col-md-9">
            <div class="container mt-4">
                <div class="card">
                    <div class="card-body">
                        <div class="card-header py-2 px-3">
                            <h4>Map</h4>
                        </div>
                            <!-- Map container -->
                        <div id="mapid"></div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Users column -->
        <div class="col-md-3">
            <div class="card people-card">
                <div class="card-header py-2 px-3">
                    <h4>People</h4>
                </div>
                <div class="card-body">
                    {% if following_list %}
                    {% for profile in following_list %}
                    <a href="{% url 'home:user_dashboard' user_id=profile.user.id %}" class="card-title"
                        style="font-weight: 600; color:black">
                        <div class="media mb-3">

                            <img src="{{ profile.profile_picture.url }}" class="mr-3 rounded-circle"
                                alt="Profile Picture" style="width: 50px; height: 50px;">
                            <div class="media-body">
                                <h5 class="mt-0">@{{profile.user.username}}</h5>
                                {{profile.location}}
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Bootstrap JS and Leaflet JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

<!-- Initialize Leaflet map -->
<script>
    var mymap = L.map('mapid');


    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        maxZoom: 8,
    }).addTo(mymap);

    var markers = L.featureGroup().addTo(mymap);
    var bounds = L.latLngBounds();
    var locations = JSON.parse('{{ locations|escapejs }}'); // Ensure this is parsed as an array
    console.log("Locations:", locations);
    for (const location of locations) {
        var lat = location[0];
        var lon = location[1];
        var tag = location[2];
        console.log("idhr hu")
        console.log(lat)


        var marker = L.marker([lat, lon]).addTo(markers)
            .bindPopup(tag)
            .openPopup();


        bounds.extend(marker.getLatLng());
    }

    mymap.fitBounds(bounds, {
        padding: [30, 30]
    });



</script>

{% endblock %}

home/templates/search.html
{% extends 'base.html' %}
{% block start %}
This is SEARCH PAGE
{% endblock %}